### ISSUE TITLE
Support finding configuration information from other platforms or config structures

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/CloudConfiguration#3]
Right now, CloudConfiguration relies very heavily on the conventions of `VCAP_SERVICES`. We should allow the configuration information to come from not only a path inside `VCAP_SERVICES`, and instead multiple paths that could be compatible with other platforms like Heroku, Amazon AWS, and our Docker deployment.

In other words, we should should support loading files with data that has been the result of something like this:

```
cf env MyApp > config.json
```

But often times, the user will want something even easier, especially the Docker case:

**Some examples:**

I think that a typical config.yml used for a Docker deployment could look like:

```yml
- port: 8080
- services:
    - postgresql
        - username: robert
        - password: pa55w0rd
        - hostname: postgresql.bluemix.net 
```
